[package]
name = "lunaro_manager"
version = "2.2.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1.89" }
chrono = { version = "0.4.45" }
dotenv = { version = "0.15.0" }
futures = { version = "0.3.32" }
log = { version = "0.4.32" }
log4rs = { version = "1.4.0" }
poise = { version = "0.6.2" }
regex = { version = "1.12.4" }
reqwest = { version = "0.13.4" }
rustc_version_runtime = { version = "0.3.0" }
serde = { version = "1.0.228" }
serde_json = { version = "1.0.150" }
thiserror = { version = "2.0.18" }
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }
tokio-util = { version = "0.7.18" }
toml = { version = "1.1.2" }
uuid = { version = "1.23.3", features = ["v4"] }
