[package]
name = "lunaro_manager"
version = "2.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
dotenv = "0.15.0"
log = "0.4.20"
log4rs = "1.2.0"
poise = { version = "0.5.5" }
regex = "1.9.4"
serde = "1.0.188"
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }
