version: "3"

services:
  lunaro-manager:
    image: "lunaro-manager"
    build: "."
    hostname: "lunaro-manager"
    container_name: "lunaro-manager"
    restart: "unless-stopped"
    volumes:
      - "./data:/mnt/app/data"
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      CLIENT_ID: "${CLIENT_ID}"
      HOME_GUILD_ID: "${HOME_GUILD_ID}"
      RTP_ROLE_ID: "${RTP_ROLE_ID}"
