version: '3'
services:
  lunaro-manager:
    image: lunaro-manager
    hostname: lunaro-manager
    container_name: lunaro-manager
    restart: unless-stopped
    build: .
    volumes:
      - "./data:/mnt/app/data"
      - "./log:/mnt/app/log"
    environment:
      CLIENT_ID: ${CLIENT_ID:-example}
      CLIENT_TOKEN: ${CLIENT_TOKEN:-example}
      HOME_GUILD_ID: ${HOME_GUILD_ID:-example}
      PLAYING_ROLE_ID: ${PLAYING_ROLE_ID:-example}
