name: lunaro_manager

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    # defaults:
    #   run:
    #     working-directory: .
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        # with:
        #   workspaces: .
      - run: cargo check
      - run: cargo test
      - run: cargo build
